nelmio_api_doc:
    documentation:
        info:
            title: StudyOn.Billing
            description: This is an API for StudyOn platform.
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: [ ]
    areas: # to filter documented areas
        path_patterns:
            - ^/api/v1(?!/doc$)
