language: php
php:
  - 7.4

cache:
  yarn: true
  directories:
    - ${HOME}/.composer/cache
    - ./bin/.phpunit

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo chown -R ${UID:-1000}:${GID:-1000} $PWD
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
  - docker -v
  - docker-compose -v

install:
  - docker-compose build
  - make install
  - ls -la

script:
  - docker-compose exec php bin/phpunit

after_script:
  - docker-compose down