#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_v1_auth:
  path:       /api/v1/auth
  controller: App\Controller\ApiLoginController::auth
  methods:    POST

api_v1_register:
  path:       /api/v1/register
  controller: App\Controller\ApiRegistrationController::register
  methods:    POST

api_v1_current_user:
  path:       /api/v1/users/current
  controller: App\Controller\ApiUserController::current
  methods:    GET

app.swagger_ui:
  path:       /api/v1/doc
  methods:    GET
  defaults:   { _controller: nelmio_api_doc.controller.swagger_ui }