#index:
#    path: /
#    controller: App\Controller\DefaultController::index



api_v1_auth:
  path:       /api/v1/auth
  controller: App\Controller\ApiLoginController::auth
  methods:    POST

api_v1_register:
  path:       /api/v1/register
  controller: App\Controller\ApiRegistrationController::register
  methods:    POST

api_v1_refresh:
  path:       /api/v1/token/refresh
  controller: App\Controller\ApiRefreshTokenController::refresh
  methods:    POST

api_v1_current_user:
  path:       /api/v1/users/current
  controller: App\Controller\ApiUserController::current
  methods:    GET

api_v1_course_create:
  path:       /api/v1/courses
  controller: App\Controller\ApiCourseController::createCourse
  methods:    POST

api_v1_course_edit:
  path:       /api/v1/courses/{code}/edit
  controller: App\Controller\ApiCourseController::editCourse
  methods:    POST

api_v1_course_delete:
  path:       /api/v1/courses/{code}/delete
  controller: App\Controller\ApiCourseController::deleteCourse
  methods:    POST

api_v1_courses:
  path:       /api/v1/courses
  controller: App\Controller\ApiCourseController::getCourses
  methods:    GET

api_v1_user_courses:
  path:       /api/v1/me/courses
  controller: App\Controller\ApiCourseController::getUserCourses
  methods:    GET

api_v1_course:
  path:       /api/v1/courses/{code}
  controller: App\Controller\ApiCourseController::getCourse
  methods:    GET

api_v1_course_buy:
  path:       /api/v1/courses/{code}/buy
  controller: App\Controller\ApiCourseController::buyCourse
  methods:    POST

api_v1_transactions:
  path:       /api/v1/transactions
  controller: App\Controller\ApiTransactionsController::getTransactions
  methods:    GET

app.swagger_ui:
  path:       /api/v1/doc
  methods:    GET
  defaults:   { _controller: nelmio_api_doc.controller.swagger_ui }